---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible molecule docker yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Install role
  - ansible-galaxy install --force -r tests/requirements.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Style check for yaml
  - find . -name "*.yml" | xargs yamllint
  # http://molecule.readthedocs.io/en/v1/
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
